[".local/share/oh-my-zsh"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh"
refreshPeriod = "168h"

[".config/bat/themes/Catppuccin Mocha.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme"
refreshPeriod = "168h"

[".config/git/delta/catppuccin.gitconfig"]
type = "file"
url = "https://github.com/catppuccin/delta/raw/refs/heads/main/catppuccin.gitconfig"
refreshPeriod = "168h"
