FROM archlinux:base-devel-20240101.0.204074

ARG USER=user
ARG GROUP=user
ARG UID=1000
ARG GID=1000

RUN pacman -Syu --noconfirm ansible

# Create the user
# hadolint ignore=DL3046
RUN groupadd -g $GID $GROUP \
  && useradd -m -u $UID -g $GID $USER \
  && echo "$USER ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

COPY . /home/$USER/.dotfiles

RUN chown -R $USER:$USER /home/$USER/.dotfiles

USER $USER
WORKDIR /home/$USER

RUN "$HOME/.dotfiles/init/setup.sh"

CMD ["/usr/bin/zsh"]
