#!/usr/bin/env bash

# bash strict mode
set -euo pipefail
IFS=$'\n\t'

BOLD='\033[1m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
GRAY='\033[1;30m'
NC='\033[0m'

error() {
	echo -e "${RED}${BOLD}✖ ${NC} $*"
}

warn() {
	echo -e "${YELLOW}${BOLD}⚠ ${NC} $*"
}

info() {
	echo -e "${BLUE}${BOLD}ℹ ${NC} ${GRAY}$*${NC}"
}

success() {
	echo -e "${GREEN}${BOLD}✔ ${NC} $*"
}

_check_nvim() {
	info "Checking nvim..."

	if ! command -v nvim &>/dev/null; then
		error "nvim not found"
		return 1
	fi

	if ! nvim --headless +q; then
		error "nvim failed to start"
		return 1
	fi

	local -r health_log="$(mktemp)"

	nvim --headless +checkhealth "+w!$health_log" +qa &>/dev/null

	local -r warnings=$(grep "WARNING" "$health_log")
	local -r errors=$(grep "ERROR" "$health_log")

	if [ "$errors" ]; then
		error "nvim health check failed"
		return 1
	fi

	if [ "$warnings" ]; then
		warn "nvim health check warnings:"

		for warning in $warnings; do
			warn "$warning"
		done
	fi

	success "nvim is healthy"
}

_dotfiles_doctor() {
	info "Running dotfiles doctor..."
	if ! _check_nvim; then
		error "dotfiles doctor failed"
		exit 1
	fi
}

_dotfiles_doctor
