---
- hosts: all
  environment:
    XDG_CONFIG_HOME: "~/.config"
    XDG_DATA_HOME: "~/.local/share"
    XDG_CACHE_HOME: "~/.cache"
    XDG_STATE_HOME: "~/.local/state"
  roles:
    - common
    - zsh
    - starship
    - zoxide
    - tmux
    - nvim
    - mise
    - rust
    - bat
    - git
    - atuin
