---
- hosts: all
  environment:
    XDG_CONFIG_HOME: "{{ ansible_env.HOME }}/.config"
    XDG_DATA_HOME: "{{ ansible_env.HOME }}/.local/share"
    XDG_CACHE_HOME: "{{ ansible_env.HOME }}/.cache"
    XDG_STATE_HOME: "{{ ansible_env.HOME }}/.local/state"
  roles:
    - common
    - zsh
    - starship
    - zoxide
    - tmux
    - nvim
