[tools]
node = 'lts'
rust = { version = "stable", profile = "minimal" }
pnpm = 'latest'
python = { version = "3.12", profile = "minimal" }
uv = 'latest'
claude = 'latest'

[settings]
experimental = true
