[tools]
node = 'lts'
rust = { version = "stable", profile = "minimal" }
pnpm = 'latest'
python = { version = "3.14", profile = "minimal" }
uv = 'latest'
claude = 'latest'
prettier = "latest"
go = "latest"
typstyle = "latest"
typst = "latest"
watchexec = "latest"
opencode = "latest"
pipx = "latest"

[settings]
experimental = true
