gui:
  nerdFontsVersion: "3"
os:
  editPreset: "nvim-remote"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
customCommands:
  - key: <c-a>
    description: Pick AI commit
    context: global
    prompts:
      - type: menuFromCommand
        title: Select AI Commit Message
        key: CommitMsg
        command: claude --model sonnet -p "/commit-message"
    command: echo "{{.Form.CommitMsg}}" > .git/LAZYGIT_PENDING_COMMIT
    output: terminal
