gui:
  nerdFontsVersion: "3"
os:
  editPreset: "nvim-remote"
customCommands:
  - key: <c-a>
    description: Pick AI commit
    context: global
    prompts:
      - type: menuFromCommand
        title: Select AI Commit Message
        key: CommitMsg
        command: claude-commit
    command: echo "{{.Form.CommitMsg}}" > .git/LAZYGIT_PENDING_COMMIT
    output: terminal
