---
- block:
  - name: "ZOXIDE | Install Zoxide"
    include_tasks: tasks/install_{{ dotfiles_os_family }}.yml
    when: dotfiles_os_family in ['archlinux']

  - name: ZOXIDE | Link ZSH plugin
    file:
      src: "{{ role_path }}/files/zoxide.plugin.zsh"
      dest: "{{ ansible_env.XDG_CONFIG_HOME }}/zsh/plugins/zoxide.plugin.zsh"
      state: link

  tags: zoxide
