# vim: filetype=hyprlang

# Execute your favorite apps at launch
exec-once = ~/.config/hypr/scripts/xdg.sh
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # For XDPH
exec-once = dbus-update-activation-environment --systemd --all # For XDPH
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # For XDPH

exec-once = ~/.config/hypr/scripts/idle.sh
exec-once = waybar
exec-once = swaync

exec-once = 1password --silent # run this in tray for ssh-agent
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

exec-once = nm-applet
exec-once = blueman-applet

exec-once = wl-paste --type text --watch cliphist store # Clipboard store text data
exec-once = wl-paste --type image --watch cliphist store # Clipboard store image data
