# vim: filetype=hyprlang

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,auto

# Some default env vars.
env = XCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = MOZ_ENABLE_WAYLAND,1
# env = GDK_SCALE,1

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = de

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 to 1.0, 0 means no modification.
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    new_is_master = true
    # Ultrawide monitor
    # orientation = center
    # always_center_master = true
    # mfact = -0.2
}

gestures {
    workspace_swipe = true
    workspace_swipe_fingers = 3
}

misc {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
}

xwayland {
    force_zero_scaling = true
}

source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/theme.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/devices.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/keybinds.conf
