# vim: filetype=hyprlang

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

windowrulev2 = float,class:^(swaync-control-center)$
windowrulev2 = layer overlay,class:^(swaync-notification-window)$

windowrulev2 = float,class:^(1Password)$,title:(Lock Screen)
windowrulev2 = size 25% 25%,class:^(1Password)$,title:(Lock Screen)
windowrulev2 = center,class:^(1Password)$,title:(Lock Screen)

$firefoxPiP = class:^(firefox)$,title:(Picture-in-Picture)
windowrulev2 = float, $firefoxPiP
windowrulev2 = pin, $firefoxPiP # show on all workspaces
windowrulev2 = keepaspectratio, $firefoxPiP

$chromePiP = title:^(Picture in picture)$
windowrulev2 = float, $chromePiP
windowrulev2 = pin, $chromePiP # show on all workspaces
windowrulev2 = keepaspectratio, $chromePiP

$runelitePiP = class:^(net-runelite-client-RuneLite)$,title:(Picture in Picture)
windowrulev2 = float, $runelitePiP
windowrulev2 = pin, $runelitePiP
windowrulev2 = nofocus, $runelitePiP
windowrulev2 = keepaspectratio, $runelitePiP
windowrulev2 = opacity 0.6, $runelitePiP
windowrulev2 = noborder, $runelitePiP
windowrulev2 = noblur, $runelitePiP
windowrulev2 = noanim, $runelitePiP

windowrulev2 = workspace 4,title:^(Spotify)


