---

- block:
  - name: Set rustup default toolchain
    command: rustup default stable
    become: true
    become_user: "{{ item }}"
    args:
      creates: ~/
    with_items: "{{ users }}"

  - name: Update rustup
    command: rustup update
    become: true
    become_user: "{{ item }}"
    with_items: "{{ users }}"

  vars:
    users:
      # - aur_builder
      - "{{ ansible_user_id }}"
