[tools]
node = "lts"
rust = { version = "stable", profile = "minimal" }
pnpm = 'latest'
python = { version = "3.14", profile = "minimal" }
uv = 'latest'
claude = 'latest'
prettier = "latest"
go = "latest"
typstyle = "latest"
typst = "latest"
watchexec = "latest"
opencode = "latest"
pipx = "latest"
glab = { version = "latest", provider = "gitlab", exe = "glab" }
"pipx:git-filter-repo" = "latest"
"npm:gitlab-ci-local" = "latest"
pre-commit = "latest"
golangci-lint = "latest"
yazi = "latest"
github-cli = "latest"
lazygit = "latest"
zellij = "latest"
"go:github.com/jorgerojas26/lazysql" = "latest"
"github:anomalyco/opencode" = "latest"
usage = "latest"
"npm:@playwright/cli" = "latest"
age = "latest"
gotestsum = "latest"
yq = "latest"

[settings]
experimental = true
lockfile = true
