#!/usr/bin/env bash

# Dotfiles
alias di='$DOTFILES/instll'
alias bbd='brew bundle dump --tap --formula --cleanup --force --verbose --file=$DOTFILES/Brewfile && brew bundle install --file=$DOTFILES/Brewfile'

# Git
alias gc='git commit'
alias gp='git push'

# Folders
alias dot='$DOTFILES'
alias code='$HOME/code'
alias notes='$HOME/notes'

# Quick access to some config files
alias ev='nvim $DOTFILES/nvim'
alias et='nvim $DOTFILES/tmux'

# Eza
alias ls="eza --icons --git"
alias l="eza -l --icons --git -a"
alias lt="eza --tree --level=2 --long --icons --git"

# zoxide
alias cd='z'
