#!/usr/bin/env bash

# Dotfiles
alias di='$DOTFILES/instll'
alias bbd='brew bundle dump --tap --formula --cleanup --force --verbose --file=$DOTFILES/Brewfile'

# Git
alias gc='git commit'

# Folders
alias dot='$DOTFILES'
alias code='$HOME/code'

# Quick access to some config files
alias ev='nvim $DOTFILES/nvim'
alias et='nvim $DOTFILES/tmux'
