# Inspiration: 
# - https://github.com/LukeSmithxyz/voidrice/blob/master/.config/shell/profile
# - https://github.com/Phantas0s/.dotfiles/blob/master/zsh/zshenv

export DOTFILES="$HOME/.dotfiles"

export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="nvimpager"

# Man pages
# export MANPAGER='nvim +Man!'
export MANPAGER='nvimpager'

# XDG
# See: https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state

# Move as many config files as possible to XDG_CONFIG_HOME
export ASDF_CONFIG_FILE="${XDG_CONFIG_HOME}/asdf/asdfrc"
export ASDF_DATA_DIR="${XDG_DATA_HOME}/asdf"
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export ANSIBLE_HOME="${XDG_CONFIG_HOME}/ansible"
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME}/ansible.cfg"
export ANSIBLE_GALAXY_CACHE_DIR="${XDG_CACHE_HOME}/ansible/galaxy_cache"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file

# Add all directories in `~/.local/bin` to $PATH
if [[ -d ~/.local/bin ]]; then
  export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"
fi

if [[ -d /home/linuxbrew/.linuxbrew ]]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
elif [[ -d ~/.linuxbrew ]]; then
  eval "$(~/.linuxbrew/bin/brew shellenv)"
elif [[ -d /opt/homebrew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi
if [[ -d "$XDG_DATA_HOME/cargo" ]]; then
  . "$XDG_DATA_HOME/cargo/env"
fi

if [[ -x "$(command -v brew)" ]]; then
  export HOMEBREW_NO_ANALYTICS=1
  export HOMEBREW_BUNDLE_NO_LOCK=1
fi

