# Inspiration: 
# - https://github.com/LukeSmithxyz/voidrice/blob/master/.config/shell/profile
# - https://github.com/Phantas0s/.dotfiles/blob/master/zsh/zshenv

export DOTFILES="$HOME/.dotfiles"

export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="nvimpager"

# Man pages
# export MANPAGER='nvim +Man!'
export MANPAGER='nvimpager'

# XDG
# See: https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state

# Move as many config files as possible to XDG_CONFIG_HOME
export ASDF_CONFIG_FILE="${XDG_CONFIG_HOME}/asdf/asdfrc"
export ASDF_DATA_DIR="${XDG_DATA_HOME}/asdf"
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file

# Add all directories in `~/.local/bin` to $PATH
export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

# Homebrew
export HOMEBREW_NO_ANALYTICS=1

[ -d /home/linuxbrew/.linuxbrew ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
[ -d ~/.linuxbrew ] && eval "$(~/.linuxbrew/bin/brew shellenv)"
[ -d /opt/homebrew ] && eval "$(/opt/homebrew/bin/brew shellenv)"
[ -d "$XDG_DATA_HOME/cargo" ] && . "$XDG_DATA_HOME/cargo/env"
