#? Config file for btop v.1.4.6

color_theme = "catppuccin_mocha"

#* Enable h,j,k,l,g,G vim-style navigation in lists.
vim_keys = true

#* Show all standard boxes including net.
shown_boxes = "cpu mem net proc"

#* Sort processes by memory usage.
proc_sorting = "memory"

#* Show processes as a tree for better hierarchy visibility.
proc_tree = true

#* Prevent btop from rewriting this file on exit.
save_config_on_exit = false
