name: 'Fresh install dotfiles'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  install-dotfiles:
    runs-on: ubuntu-latest
    # The `steps` key groups together all the steps that will run as part of the `check-links` job. Each job in a workflow has its own `steps` section.
    steps:
      # The `uses` key tells the job to retrieve the action named `actions/checkout`. This is an action that checks out your repository and downloads it to the runner, allowing you to run actions against your code (such as testing tools). You must use the checkout action any time your workflow will use the repository's code or you are using an action defined in the repository.
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Cache Homebrew
        id: cache-homebrew
        uses: actions/cache@v4
        with:
          path: |
            /home/linuxbrew/.linuxbrew
            /root/.asdf
          key: ${{ runner.os }}-homebrew

      - name: Install Homebrew
        id: install-homebrew
        if: steps.cache-homebrew.outputs.cache-hit != 'true'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      # - name: Install zsh
      #   id: install-zsh
      #   run: |
      #     eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      #     brew install zsh
      #     ln -s $(which zsh) /usr/bin/zsh

      - name: Bootstrap dotfiles
        id: bootstrap-dotfiles
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          ln -sf $GITHUB_WORKSPACE $HOME/.dotfiles
          ./install

      - name: Verify
        id: verify
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          zsh --version
          zsh -c "echo Hello World"
          zsh -c "env"
          zsh -c "nvim --headless +q"



      # - name: Check nvim
      #   id: check-nvim
      #   run: |
      #     eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      #     zsh -c "nvim --headless +q"
