name: 'Fresh install dotfiles'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  HOMEBREW_NO_ANALYTICS: 1

jobs:
  install-dotfiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Homebrew
        id: cache-homebrew
        uses: actions/cache@v4
        with:
          path: |
            /home/linuxbrew/.linuxbrew
            /root/.asdf
          key: ${{ runner.os }}-homebrew

      - name: Install Homebrew
        id: install-homebrew
        if: steps.cache-homebrew.outputs.cache-hit != 'true'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Setup Homebrew env
        id: setup-homebrew-env
        run: |
          # add all relevant env to github actions env
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "HOMEBREW_PREFIX=$HOMEBREW_PREFIX" >> "$GITHUB_ENV"
          echo "HOMEBREW_CELLAR=$HOMEBREW_CELLAR" >> "$GITHUB_ENV"
          echo "HOMEBREW_REPOSITORY=$HOMEBREW_REPOSITORY" >> "$GITHUB_ENV"
          echo "$HOMEBREW_PREFIX/bin:$HOMEBREW_PREFIX/sbin" >> "$GITHUB_PATH"

      - name: Bootstrap dotfiles
        id: bootstrap-dotfiles
        run: |
          # symlink the dotfiles to the current users home directory
          ln -sf $GITHUB_WORKSPACE $HOME/.dotfiles
          ./install

      - name: Verify
        id: verify
        shell: zsh {0}
        run: |
          # zsh is available
          zsh --version

          tmux -V
          asdf --version
          node --version
          fzf --version
          gh --version
          nvim --version

          # TODO implement more checks
