name: 'Fresh install dotfiles'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  install-dotfiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Homebrew
        id: cache-homebrew
        uses: actions/cache@v4
        with:
          path: |
            /home/linuxbrew/.linuxbrew
            /root/.asdf
          key: ${{ runner.os }}-homebrew

      - name: Install Homebrew
        id: install-homebrew
        if: steps.cache-homebrew.outputs.cache-hit != 'true'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Bootstrap dotfiles
        id: bootstrap-dotfiles
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          ln -sf $GITHUB_WORKSPACE $HOME/.dotfiles
          ./install

      - name: Verify
        id: verify
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          # zsh is available
          zsh --version

          # headless install nvim
          zsh -c "nvim --headless +q"

          # TODO implement more checks
